@startuml

SystemHandler "0..n" *--> Publisher
SystemHandler "0..n" *--> Subscriber
SystemHandler *--> Participant

Participant <-- Publisher
Participant <-- Subscriber
Participant "0..n" *--> TopicType

Publisher ..> Conversion
Subscriber ..> Conversion

class SystemHandler {
    + configure() override
    + okay() override
    + spin_once() override
    + subscribe() override
    + advertise() override
}

class Participant {
    - dds::participant
    + create_topic_type(name)
}

class TopicType {
    - dds::type
    + create_dynamic_data()
}

class Publisher {
    - dds::Publisher
    - topic_name
    - message_type
    + publish(soss_message)
}

class Subscriber {
    - dds::subscriber
    - topic_name
    - message_type
    + receive(dynamic_type_message)
}

class Conversion << (S,#FF7700) Singleton >> {
    + dds_message soss_to_dds(soss_message)
    + soss_message dds_to_soss(dds_message)
}

@enduml

