@startuml
actor other_sh
actor soss_core
participant SystemHandle
participant Participant
participant Publisher
participant Subscriber
participant Conversion
entity dds

== initialization ==
soss_core -> SystemHandle: configure
activate SystemHandle
SystemHandle -> Participant: __init__()
SystemHandle -> Participant: register_dynamic_type()
activate Participant
Participant -> Participant: register_type()
SystemHandle <-- Participant: status
deactivate Participant
soss_core <-- SystemHandle: status
deactivate SystemHandle

soss_core -> SystemHandle: advertise
activate SystemHandle
SystemHandle -> Publisher: __init__()
soss_core <-- SystemHandle: TopicPublisher
deactivate SystemHandle

soss_core -> SystemHandle: subscribe
activate SystemHandle
SystemHandle -> Subscriber: __init__()
soss_core <-- SystemHandle: status
deactivate SystemHandle

soss_core -> SystemHandle: spin_once
activate SystemHandle
soss_core <-- SystemHandle: status
deactivate SystemHandle

== to dds ==
other_sh -> Publisher: publish()
activate Publisher
Publisher -> Conversion: soss_to_dds()
activate Conversion
Publisher <-- Conversion: dds_topic
deactivate Conversion
Publisher -[#0000FF]> dds: send_to_dds()
other_sh <-- Publisher: status
deactivate Publisher

== from dds ==
dds -[#0000FF]> Subscriber: receive_from_dds()
activate Subscriber
Subscriber -> Conversion: dds_to_soss()
activate Conversion
Subscriber <-- Conversion: soss_topic
deactivate Conversion
Subscriber -> other_sh: soss_subscription_cb
deactivate Subscriber

== while running ==
soss_core -> SystemHandle: spin_once
activate SystemHandle
SystemHandle -> SystemHandle: wait_100ms()
soss_core <-- SystemHandle: status
deactivate SystemHandle

== destruction ==
soss_core -> SystemHandle: __destroy__()
activate SystemHandle
SystemHandle -> Subscriber: __destroy__()
SystemHandle -> Publisher: __destroy__()
SystemHandle -> Participant: __destroy__()
activate Participant
Participant -> Participant: unregister_type()
deactivate Participant
deactivate SystemHandle

@enduml

