name: Ubuntu test
description: Download and install Integration Service and FastDDS with specific version and test repo FastDDS-SH
inputs:
  fastddsVersion:
    description: 'FastDDS version'
    required: false
    default: 'master'
runs:
  using: composite

  steps:
      - uses: actions/checkout@v2
        with:
          path: src/fastdds-sh

      - name: Download required dependencies
        run: |
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y cmake gcc g++ git libboost-dev libboost-program-options-dev libyaml-cpp-dev

      - name: Install colcon
        run: |
          apt install -y python3-pip
          pip3 install -U colcon-common-extensions

      - name: Download the Integration Service
        run: |
          git clone --recursive https://github.com/eProsima/Integration-Service src/integration-service

      - name: Download FastDDS
        run: |
          git clone -b ${INPUT_FASTDDSVERSION} https://github.com/eProsima/Fast-DDS src/integration-service

      - name: Build
        run: |
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_FASTDDS_TESTS=ON --event-handlers console_direct+

      - name: Test
        run: |
          . install/local_setup.sh && colcon test --packages-up-to is-fastdds --event-handlers console_direct+
          colcon test-result
