// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file test_service.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "test_service.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

Method0_In::Method0_In()
{
    // m_data com.eprosima.idl.parser.typecode.StringTypeCode@5abca1e0
    m_data ="";

}

Method0_In::~Method0_In()
{
}

Method0_In::Method0_In(const Method0_In &x)
{
    m_data = x.m_data;
}

Method0_In::Method0_In(Method0_In &&x)
{
    m_data = std::move(x.m_data);
}

Method0_In& Method0_In::operator=(const Method0_In &x)
{

    m_data = x.m_data;

    return *this;
}

Method0_In& Method0_In::operator=(Method0_In &&x)
{

    m_data = std::move(x.m_data);

    return *this;
}

size_t Method0_In::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    return current_alignment - initial_alignment;
}

size_t Method0_In::getCdrSerializedSize(const Method0_In& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.data().size() + 1;

    return current_alignment - initial_alignment;
}

void Method0_In::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_data;
}

void Method0_In::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_data;
}

/*!
 * @brief This function copies the value in member data
 * @param _data New value to be copied in member data
 */
void Method0_In::data(const std::string &_data)
{
m_data = _data;
}

/*!
 * @brief This function moves the value in member data
 * @param _data New value to be moved in member data
 */
void Method0_In::data(std::string &&_data)
{
m_data = std::move(_data);
}

/*!
 * @brief This function returns a constant reference to member data
 * @return Constant reference to member data
 */
const std::string& Method0_In::data() const
{
    return m_data;
}

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
std::string& Method0_In::data()
{
    return m_data;
}

size_t Method0_In::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool Method0_In::isKeyDefined()
{
   return false;
}

void Method0_In::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
    (void) scdr;
     
}

Method1_In::Method1_In()
{
    // m_a com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1f28c152
    m_a = 0;
    // m_b com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7791a895
    m_b = 0;

}

Method1_In::~Method1_In()
{


}

Method1_In::Method1_In(const Method1_In &x)
{
    m_a = x.m_a;
    m_b = x.m_b;
}

Method1_In::Method1_In(Method1_In &&x)
{
    m_a = x.m_a;
    m_b = x.m_b;
}

Method1_In& Method1_In::operator=(const Method1_In &x)
{

    m_a = x.m_a;
    m_b = x.m_b;

    return *this;
}

Method1_In& Method1_In::operator=(Method1_In &&x)
{

    m_a = x.m_a;
    m_b = x.m_b;

    return *this;
}

size_t Method1_In::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t Method1_In::getCdrSerializedSize(const Method1_In& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void Method1_In::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_a;
    scdr << m_b;
}

void Method1_In::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_a;
    dcdr >> m_b;
}

/*!
 * @brief This function sets a value in member a
 * @param _a New value for member a
 */
void Method1_In::a(int32_t _a)
{
m_a = _a;
}

/*!
 * @brief This function returns the value of member a
 * @return Value of member a
 */
int32_t Method1_In::a() const
{
    return m_a;
}

/*!
 * @brief This function returns a reference to member a
 * @return Reference to member a
 */
int32_t& Method1_In::a()
{
    return m_a;
}

/*!
 * @brief This function sets a value in member b
 * @param _b New value for member b
 */
void Method1_In::b(int32_t _b)
{
m_b = _b;
}

/*!
 * @brief This function returns the value of member b
 * @return Value of member b
 */
int32_t Method1_In::b() const
{
    return m_b;
}

/*!
 * @brief This function returns a reference to member b
 * @return Reference to member b
 */
int32_t& Method1_In::b()
{
    return m_b;
}


size_t Method1_In::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool Method1_In::isKeyDefined()
{
   return false;
}

void Method1_In::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
    (void) scdr;
     
     
}

Method2_In::Method2_In()
{
    // m_data com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1d16f93d
    m_data = 0.0;

}

Method2_In::~Method2_In()
{
}

Method2_In::Method2_In(const Method2_In &x)
{
    m_data = x.m_data;
}

Method2_In::Method2_In(Method2_In &&x)
{
    m_data = x.m_data;
}

Method2_In& Method2_In::operator=(const Method2_In &x)
{

    m_data = x.m_data;

    return *this;
}

Method2_In& Method2_In::operator=(Method2_In &&x)
{

    m_data = x.m_data;

    return *this;
}

size_t Method2_In::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

size_t Method2_In::getCdrSerializedSize(const Method2_In& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

void Method2_In::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_data;
}

void Method2_In::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_data;
}

/*!
 * @brief This function sets a value in member data
 * @param _data New value for member data
 */
void Method2_In::data(float _data)
{
m_data = _data;
}

/*!
 * @brief This function returns the value of member data
 * @return Value of member data
 */
float Method2_In::data() const
{
    return m_data;
}

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
float& Method2_In::data()
{
    return m_data;
}


size_t Method2_In::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool Method2_In::isKeyDefined()
{
   return false;
}

void Method2_In::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
    (void) scdr;
     
}

TestService_Call::TestService_Call()
{
    m__d = 0;
    // m_method0 com.eprosima.fastrtps.idl.parser.typecode.StructTypeCode@23d2a7e8

    // m_method1 com.eprosima.fastrtps.idl.parser.typecode.StructTypeCode@7a9273a8

    // m_method2 com.eprosima.fastrtps.idl.parser.typecode.StructTypeCode@26a7b76d

}

TestService_Call::~TestService_Call()
{
}

TestService_Call::TestService_Call(const TestService_Call &x)
{
    m__d = x.m__d;

    switch(m__d)
    {
        case 0:
        m_method0 = x.m_method0;
        break;
        case 1:
        m_method1 = x.m_method1;
        break;
        case 2:
        m_method2 = x.m_method2;
        break;
        default:
        break;
    }
}

TestService_Call::TestService_Call(TestService_Call &&x)
{
    m__d = x.m__d;

    switch(m__d)
    {
        case 0:
        m_method0 = std::move(x.m_method0);
        break;
        case 1:
        m_method1 = std::move(x.m_method1);
        break;
        case 2:
        m_method2 = std::move(x.m_method2);
        break;
        default:
        break;
    }
}

TestService_Call& TestService_Call::operator=(const TestService_Call &x)
{
    m__d = x.m__d;

    switch(m__d)
    {
        case 0:
        m_method0 = x.m_method0;
        break;
        case 1:
        m_method1 = x.m_method1;
        break;
        case 2:
        m_method2 = x.m_method2;
        break;
        default:
        break;
    }

    return *this;
}

TestService_Call& TestService_Call::operator=(TestService_Call &&x)
{
    m__d = x.m__d;

    switch(m__d)
    {
        case 0:
        m_method0 = std::move(x.m_method0);
        break;
        case 1:
        m_method1 = std::move(x.m_method1);
        break;
        case 2:
        m_method2 = std::move(x.m_method2);
        break;
        default:
        break;
    }

    return *this;
}

void TestService_Call::_d(uint32_t __d)
{
    bool b = false;

    switch(m__d)
    {
        case 0:
        switch(__d)
        {
            case 0:
            b = true;
            break;
            default:
            break;
        }
        break;
        case 1:
        switch(__d)
        {
            case 1:
            b = true;
            break;
            default:
            break;
        }
        break;
        case 2:
        switch(__d)
        {
            case 2:
            b = true;
            break;
            default:
            break;
        }
        break;
    }

    if(!b)
    {
        throw BadParamException("Discriminator doesn't correspond with the selected union member");
    }

    m__d = __d;
}

uint32_t TestService_Call::_d() const
{
    return m__d;
}

uint32_t& TestService_Call::_d()
{
    return m__d;
}

void TestService_Call::method0(const Method0_In &_method0)
{
    m_method0 = _method0;
    m__d = 0;
}

void TestService_Call::method0(Method0_In &&_method0)
{
    m_method0 = std::move(_method0);
    m__d = 0;
}

const Method0_In& TestService_Call::method0() const
{
    bool b = false;

    switch(m__d)
    {
        case 0:
        b = true;
        break;
        default:
        break;
    }
    if(!b)
    {
        throw BadParamException("This member is not been selected");
    }

    return m_method0;
}

Method0_In& TestService_Call::method0()
{
    bool b = false;

    switch(m__d)
    {
        case 0:
        b = true;
        break;
        default:
        break;
    }
    if(!b)
    {
        throw BadParamException("This member is not been selected");
    }

    return m_method0;
}
void TestService_Call::method1(const Method1_In &_method1)
{
    m_method1 = _method1;
    m__d = 1;
}

void TestService_Call::method1(Method1_In &&_method1)
{
    m_method1 = std::move(_method1);
    m__d = 1;
}

const Method1_In& TestService_Call::method1() const
{
    bool b = false;

    switch(m__d)
    {
        case 1:
        b = true;
        break;
        default:
        break;
    }
    if(!b)
    {
        throw BadParamException("This member is not been selected");
    }

    return m_method1;
}

Method1_In& TestService_Call::method1()
{
    bool b = false;

    switch(m__d)
    {
        case 1:
        b = true;
        break;
        default:
        break;
    }
    if(!b)
    {
        throw BadParamException("This member is not been selected");
    }

    return m_method1;
}
void TestService_Call::method2(const Method2_In &_method2)
{
    m_method2 = _method2;
    m__d = 2;
}

void TestService_Call::method2(Method2_In &&_method2)
{
    m_method2 = std::move(_method2);
    m__d = 2;
}

const Method2_In& TestService_Call::method2() const
{
    bool b = false;

    switch(m__d)
    {
        case 2:
        b = true;
        break;
        default:
        break;
    }
    if(!b)
    {
        throw BadParamException("This member is not been selected");
    }

    return m_method2;
}

Method2_In& TestService_Call::method2()
{
    bool b = false;

    switch(m__d)
    {
        case 2:
        b = true;
        break;
        default:
        break;
    }
    if(!b)
    {
        throw BadParamException("This member is not been selected");
    }

    return m_method2;
}

size_t TestService_Call::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
    size_t reset_alignment = 0;
    size_t union_max_size_serialized = 0;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


        reset_alignment = current_alignment;

        reset_alignment += Method0_In::getMaxCdrSerializedSize(reset_alignment);

        if(union_max_size_serialized < reset_alignment)
            union_max_size_serialized = reset_alignment;

        
        reset_alignment = current_alignment;

        reset_alignment += Method1_In::getMaxCdrSerializedSize(reset_alignment);

        if(union_max_size_serialized < reset_alignment)
            union_max_size_serialized = reset_alignment;

        
        reset_alignment = current_alignment;

        reset_alignment += Method2_In::getMaxCdrSerializedSize(reset_alignment);

        if(union_max_size_serialized < reset_alignment)
            union_max_size_serialized = reset_alignment;

        

    return union_max_size_serialized - initial_alignment;
}

// TODO(Ricardo) Review
size_t TestService_Call::getCdrSerializedSize(const TestService_Call& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    switch(data.m__d)
    {
        case 0:
        current_alignment += Method0_In::getCdrSerializedSize(data.method0(), current_alignment);
        break;
        case 1:
        current_alignment += Method1_In::getCdrSerializedSize(data.method1(), current_alignment);
        break;
        case 2:
        current_alignment += Method2_In::getCdrSerializedSize(data.method2(), current_alignment);
        break;
        default:
        break;
    }

    return current_alignment - initial_alignment;
}

void TestService_Call::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m__d;

    switch(m__d)
    {
        case 0:
        scdr << m_method0;
        break;
        case 1:
        scdr << m_method1;
        break;
        case 2:
        scdr << m_method2;
        break;
        default:
        break;
    }
}

void TestService_Call::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m__d;

    switch(m__d)
    {
        case 0:
        dcdr >> m_method0;
        break;
        case 1:
        dcdr >> m_method1;
        break;
        case 2:
        dcdr >> m_method2;
        break;
        default:
        break;
    }
}


Method0_Result::Method0_Result()
{
    // m_success com.eprosima.idl.parser.typecode.PrimitiveTypeCode@6043cd28
    m_success = false;

}

Method0_Result::~Method0_Result()
{
}

Method0_Result::Method0_Result(const Method0_Result &x)
{
    m_success = x.m_success;
}

Method0_Result::Method0_Result(Method0_Result &&x)
{
    m_success = x.m_success;
}

Method0_Result& Method0_Result::operator=(const Method0_Result &x)
{

    m_success = x.m_success;

    return *this;
}

Method0_Result& Method0_Result::operator=(Method0_Result &&x)
{

    m_success = x.m_success;

    return *this;
}

size_t Method0_Result::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

size_t Method0_Result::getCdrSerializedSize(const Method0_Result& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

void Method0_Result::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_success;
}

void Method0_Result::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_success;
}

/*!
 * @brief This function sets a value in member success
 * @param _success New value for member success
 */
void Method0_Result::success(bool _success)
{
m_success = _success;
}

/*!
 * @brief This function returns the value of member success
 * @return Value of member success
 */
bool Method0_Result::success() const
{
    return m_success;
}

/*!
 * @brief This function returns a reference to member success
 * @return Reference to member success
 */
bool& Method0_Result::success()
{
    return m_success;
}


size_t Method0_Result::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool Method0_Result::isKeyDefined()
{
   return false;
}

void Method0_Result::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
    (void) scdr;
     
}

Method1_Result::Method1_Result()
{
    // m_result com.eprosima.idl.parser.typecode.PrimitiveTypeCode@cb51256
    m_result = 0;

}

Method1_Result::~Method1_Result()
{
}

Method1_Result::Method1_Result(const Method1_Result &x)
{
    m_result = x.m_result;
}

Method1_Result::Method1_Result(Method1_Result &&x)
{
    m_result = x.m_result;
}

Method1_Result& Method1_Result::operator=(const Method1_Result &x)
{

    m_result = x.m_result;

    return *this;
}

Method1_Result& Method1_Result::operator=(Method1_Result &&x)
{

    m_result = x.m_result;

    return *this;
}

size_t Method1_Result::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

size_t Method1_Result::getCdrSerializedSize(const Method1_Result& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

void Method1_Result::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_result;
}

void Method1_Result::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_result;
}

/*!
 * @brief This function sets a value in member result
 * @param _result New value for member result
 */
void Method1_Result::result(int32_t _result)
{
m_result = _result;
}

/*!
 * @brief This function returns the value of member result
 * @return Value of member result
 */
int32_t Method1_Result::result() const
{
    return m_result;
}

/*!
 * @brief This function returns a reference to member result
 * @return Reference to member result
 */
int32_t& Method1_Result::result()
{
    return m_result;
}


size_t Method1_Result::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool Method1_Result::isKeyDefined()
{
   return false;
}

void Method1_Result::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
    (void) scdr;
     
}

Method2_Result::Method2_Result()
{
    // m_data com.eprosima.idl.parser.typecode.PrimitiveTypeCode@59906517
    m_data = 0.0;

}

Method2_Result::~Method2_Result()
{
}

Method2_Result::Method2_Result(const Method2_Result &x)
{
    m_data = x.m_data;
}

Method2_Result::Method2_Result(Method2_Result &&x)
{
    m_data = x.m_data;
}

Method2_Result& Method2_Result::operator=(const Method2_Result &x)
{

    m_data = x.m_data;

    return *this;
}

Method2_Result& Method2_Result::operator=(Method2_Result &&x)
{

    m_data = x.m_data;

    return *this;
}

size_t Method2_Result::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

size_t Method2_Result::getCdrSerializedSize(const Method2_Result& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

void Method2_Result::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_data;
}

void Method2_Result::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_data;
}

/*!
 * @brief This function sets a value in member data
 * @param _data New value for member data
 */
void Method2_Result::data(float _data)
{
m_data = _data;
}

/*!
 * @brief This function returns the value of member data
 * @return Value of member data
 */
float Method2_Result::data() const
{
    return m_data;
}

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
float& Method2_Result::data()
{
    return m_data;
}


size_t Method2_Result::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool Method2_Result::isKeyDefined()
{
   return false;
}

void Method2_Result::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
    (void) scdr;
     
}

TestService_Return::TestService_Return()
{
    m__d = 0;
    // m_method0 com.eprosima.fastrtps.idl.parser.typecode.StructTypeCode@5bcea91b

    // m_method1 com.eprosima.fastrtps.idl.parser.typecode.StructTypeCode@5f3a4b84

    // m_method2 com.eprosima.fastrtps.idl.parser.typecode.StructTypeCode@27f723

}

TestService_Return::~TestService_Return()
{
}

TestService_Return::TestService_Return(const TestService_Return &x)
{
    m__d = x.m__d;

    switch(m__d)
    {
        case 0:
        m_method0 = x.m_method0;
        break;
        case 1:
        m_method1 = x.m_method1;
        break;
        case 2:
        m_method2 = x.m_method2;
        break;
        default:
        break;
    }
}

TestService_Return::TestService_Return(TestService_Return &&x)
{
    m__d = x.m__d;

    switch(m__d)
    {
        case 0:
        m_method0 = std::move(x.m_method0);
        break;
        case 1:
        m_method1 = std::move(x.m_method1);
        break;
        case 2:
        m_method2 = std::move(x.m_method2);
        break;
        default:
        break;
    }
}

TestService_Return& TestService_Return::operator=(const TestService_Return &x)
{
    m__d = x.m__d;

    switch(m__d)
    {
        case 0:
        m_method0 = x.m_method0;
        break;
        case 1:
        m_method1 = x.m_method1;
        break;
        case 2:
        m_method2 = x.m_method2;
        break;
        default:
        break;
    }

    return *this;
}

TestService_Return& TestService_Return::operator=(TestService_Return &&x)
{
    m__d = x.m__d;

    switch(m__d)
    {
        case 0:
        m_method0 = std::move(x.m_method0);
        break;
        case 1:
        m_method1 = std::move(x.m_method1);
        break;
        case 2:
        m_method2 = std::move(x.m_method2);
        break;
        default:
        break;
    }

    return *this;
}

void TestService_Return::_d(int32_t __d)
{
    bool b = false;

    switch(m__d)
    {
        case 0:
        switch(__d)
        {
            case 0:
            b = true;
            break;
            default:
            break;
        }
        break;
        case 1:
        switch(__d)
        {
            case 1:
            b = true;
            break;
            default:
            break;
        }
        break;
        case 2:
        switch(__d)
        {
            case 2:
            b = true;
            break;
            default:
            break;
        }
        break;
    }

    if(!b)
    {
        throw BadParamException("Discriminator doesn't correspond with the selected union member");
    }

    m__d = __d;
}

int32_t TestService_Return::_d() const
{
    return m__d;
}

int32_t& TestService_Return::_d()
{
    return m__d;
}

void TestService_Return::method0(const Method0_Result &_method0)
{
    m_method0 = _method0;
    m__d = 0;
}

void TestService_Return::method0(Method0_Result &&_method0)
{
    m_method0 = std::move(_method0);
    m__d = 0;
}

const Method0_Result& TestService_Return::method0() const
{
    bool b = false;

    switch(m__d)
    {
        case 0:
        b = true;
        break;
        default:
        break;
    }
    if(!b)
    {
        throw BadParamException("This member is not been selected");
    }

    return m_method0;
}

Method0_Result& TestService_Return::method0()
{
    bool b = false;

    switch(m__d)
    {
        case 0:
        b = true;
        break;
        default:
        break;
    }
    if(!b)
    {
        throw BadParamException("This member is not been selected");
    }

    return m_method0;
}
void TestService_Return::method1(const Method1_Result &_method1)
{
    m_method1 = _method1;
    m__d = 1;
}

void TestService_Return::method1(Method1_Result &&_method1)
{
    m_method1 = std::move(_method1);
    m__d = 1;
}

const Method1_Result& TestService_Return::method1() const
{
    bool b = false;

    switch(m__d)
    {
        case 1:
        b = true;
        break;
        default:
        break;
    }
    if(!b)
    {
        throw BadParamException("This member is not been selected");
    }

    return m_method1;
}

Method1_Result& TestService_Return::method1()
{
    bool b = false;

    switch(m__d)
    {
        case 1:
        b = true;
        break;
        default:
        break;
    }
    if(!b)
    {
        throw BadParamException("This member is not been selected");
    }

    return m_method1;
}
void TestService_Return::method2(const Method2_Result &_method2)
{
    m_method2 = _method2;
    m__d = 2;
}

void TestService_Return::method2(Method2_Result &&_method2)
{
    m_method2 = std::move(_method2);
    m__d = 2;
}

const Method2_Result& TestService_Return::method2() const
{
    bool b = false;

    switch(m__d)
    {
        case 2:
        b = true;
        break;
        default:
        break;
    }
    if(!b)
    {
        throw BadParamException("This member is not been selected");
    }

    return m_method2;
}

Method2_Result& TestService_Return::method2()
{
    bool b = false;

    switch(m__d)
    {
        case 2:
        b = true;
        break;
        default:
        break;
    }
    if(!b)
    {
        throw BadParamException("This member is not been selected");
    }

    return m_method2;
}

size_t TestService_Return::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
    size_t reset_alignment = 0;
    size_t union_max_size_serialized = 0;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


        reset_alignment = current_alignment;

        reset_alignment += Method0_Result::getMaxCdrSerializedSize(reset_alignment);

        if(union_max_size_serialized < reset_alignment)
            union_max_size_serialized = reset_alignment;

        
        reset_alignment = current_alignment;

        reset_alignment += Method1_Result::getMaxCdrSerializedSize(reset_alignment);

        if(union_max_size_serialized < reset_alignment)
            union_max_size_serialized = reset_alignment;

        
        reset_alignment = current_alignment;

        reset_alignment += Method2_Result::getMaxCdrSerializedSize(reset_alignment);

        if(union_max_size_serialized < reset_alignment)
            union_max_size_serialized = reset_alignment;

        

    return union_max_size_serialized - initial_alignment;
}

// TODO(Ricardo) Review
size_t TestService_Return::getCdrSerializedSize(const TestService_Return& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    switch(data.m__d)
    {
        case 0:
        current_alignment += Method0_Result::getCdrSerializedSize(data.method0(), current_alignment);
        break;
        case 1:
        current_alignment += Method1_Result::getCdrSerializedSize(data.method1(), current_alignment);
        break;
        case 2:
        current_alignment += Method2_Result::getCdrSerializedSize(data.method2(), current_alignment);
        break;
        default:
        break;
    }

    return current_alignment - initial_alignment;
}

void TestService_Return::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m__d;

    switch(m__d)
    {
        case 0:
        scdr << m_method0;
        break;
        case 1:
        scdr << m_method1;
        break;
        case 2:
        scdr << m_method2;
        break;
        default:
        break;
    }
}

void TestService_Return::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m__d;

    switch(m__d)
    {
        case 0:
        dcdr >> m_method0;
        break;
        case 1:
        dcdr >> m_method1;
        break;
        case 2:
        dcdr >> m_method2;
        break;
        default:
        break;
    }
}


TestService_Request::TestService_Request()
{
    // m_data com.eprosima.idl.parser.typecode.UnionTypeCode@13c27452


}

TestService_Request::~TestService_Request()
{
}

TestService_Request::TestService_Request(const TestService_Request &x)
{
    m_data = x.m_data;
}

TestService_Request::TestService_Request(TestService_Request &&x)
{
    m_data = std::move(x.m_data);
}

TestService_Request& TestService_Request::operator=(const TestService_Request &x)
{

    m_data = x.m_data;

    return *this;
}

TestService_Request& TestService_Request::operator=(TestService_Request &&x)
{

    m_data = std::move(x.m_data);

    return *this;
}

size_t TestService_Request::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += TestService_Call::getMaxCdrSerializedSize(current_alignment);

    return current_alignment - initial_alignment;
}

size_t TestService_Request::getCdrSerializedSize(const TestService_Request& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += TestService_Call::getCdrSerializedSize(data.data(), current_alignment);

    return current_alignment - initial_alignment;
}

void TestService_Request::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_data;
}

void TestService_Request::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_data;
}

/*!
 * @brief This function copies the value in member data
 * @param _data New value to be copied in member data
 */
void TestService_Request::data(const TestService_Call &_data)
{
m_data = _data;
}

/*!
 * @brief This function moves the value in member data
 * @param _data New value to be moved in member data
 */
void TestService_Request::data(TestService_Call &&_data)
{
m_data = std::move(_data);
}

/*!
 * @brief This function returns a constant reference to member data
 * @return Constant reference to member data
 */
const TestService_Call& TestService_Request::data() const
{
    return m_data;
}

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
TestService_Call& TestService_Request::data()
{
    return m_data;
}

size_t TestService_Request::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool TestService_Request::isKeyDefined()
{
   return false;
}

void TestService_Request::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
    (void) scdr;
     
}

TestService_Reply::TestService_Reply()
{
    // m_reply com.eprosima.idl.parser.typecode.UnionTypeCode@5ed828d


}

TestService_Reply::~TestService_Reply()
{
}

TestService_Reply::TestService_Reply(const TestService_Reply &x)
{
    m_reply = x.m_reply;
}

TestService_Reply::TestService_Reply(TestService_Reply &&x)
{
    m_reply = std::move(x.m_reply);
}

TestService_Reply& TestService_Reply::operator=(const TestService_Reply &x)
{

    m_reply = x.m_reply;

    return *this;
}

TestService_Reply& TestService_Reply::operator=(TestService_Reply &&x)
{

    m_reply = std::move(x.m_reply);

    return *this;
}

size_t TestService_Reply::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += TestService_Return::getMaxCdrSerializedSize(current_alignment);

    return current_alignment - initial_alignment;
}

size_t TestService_Reply::getCdrSerializedSize(const TestService_Reply& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += TestService_Return::getCdrSerializedSize(data.reply(), current_alignment);

    return current_alignment - initial_alignment;
}

void TestService_Reply::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_reply;
}

void TestService_Reply::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_reply;
}

/*!
 * @brief This function copies the value in member reply
 * @param _reply New value to be copied in member reply
 */
void TestService_Reply::reply(const TestService_Return &_reply)
{
m_reply = _reply;
}

/*!
 * @brief This function moves the value in member reply
 * @param _reply New value to be moved in member reply
 */
void TestService_Reply::reply(TestService_Return &&_reply)
{
m_reply = std::move(_reply);
}

/*!
 * @brief This function returns a constant reference to member reply
 * @return Constant reference to member reply
 */
const TestService_Return& TestService_Reply::reply() const
{
    return m_reply;
}

/*!
 * @brief This function returns a reference to member reply
 * @return Reference to member reply
 */
TestService_Return& TestService_Reply::reply()
{
    return m_reply;
}

size_t TestService_Reply::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool TestService_Reply::isKeyDefined()
{
   return false;
}

void TestService_Reply::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
    (void) scdr;
     
}
